# Generated by Django 4.2.30 on 2026-09-17 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Churches',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Counties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('surname', models.CharField(max_length=100)),
                ('other_names', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('home_town', models.CharField(blank=True, max_length=150)),
                ('religion', models.CharField(blank=True, max_length=100)),
                ('experience', models.CharField(blank=True, max_length=200)),
                ('gift', models.CharField(blank=True, max_length=150)),
                ('referee_name', models.CharField(blank=True, max_length=150)),
                ('referee_phone', models.CharField(blank=True, max_length=20)),
                ('referee_location', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='members.church')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='members.county')),
                ('departments', models.ManyToManyField(blank=True, related_name='members', to='members.department')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MembershipNumberCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_number_prefix', models.CharField(default='EGUP', max_length=10)),
                ('membership_number_width', models.PositiveSmallIntegerField(default=6)),
                ('membership_fee_kes', models.PositiveIntegerField(default=200)),
                ('renewal_fee_kes', models.PositiveIntegerField(default=100)),
                ('automatic_payment_enabled', models.BooleanField(default=False, help_text="Show 'Pay with M-Pesa' (STK push via PayHero) as an option. Requires PayHero credentials to be configured (env vars or Finance > Payment Credentials) — see is_automatic_payment_available().")),
                ('manual_payment_enabled', models.BooleanField(default=True, help_text="Show 'Pay manually' (M-Pesa PayBill/Till + transaction code, admin-verified) as an option.")),
                ('manual_payment_paybill', models.CharField(blank=True, default='247247', help_text='Official EGUP M-Pesa PayBill number.', max_length=20)),
                ('manual_payment_till', models.CharField(blank=True, help_text='Leave blank if using a PayBill instead.', max_length=20)),
                ('manual_payment_account_note', models.CharField(blank=True, default='100658', help_text='Official EGUP M-Pesa account number, shown to applicants exactly as entered here.', max_length=255)),
                ('manual_payment_instructions', models.TextField(blank=True, help_text='Extra instructions shown above the manual payment form, e.g. business name confirmation text.')),
                ('manual_payment_screenshot_required', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='RenewalAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_authorizations', to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('other_names', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('home_town', models.CharField(blank=True, max_length=150)),
                ('religion', models.CharField(blank=True, max_length=100)),
                ('experience', models.CharField(blank=True, max_length=200)),
                ('gift', models.CharField(blank=True, max_length=150)),
                ('referee_name', models.CharField(blank=True, max_length=150)),
                ('referee_phone', models.CharField(blank=True, max_length=20)),
                ('referee_location', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending payment'), ('SETTLED', 'Settled (member created)'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING_PAYMENT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_intents', to='members.church')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registration_intents', to='members.county')),
                ('departments', models.ManyToManyField(blank=True, related_name='registration_intents', to='members.department')),
                ('profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_intents', to='members.profession')),
                ('skills', models.ManyToManyField(blank=True, related_name='registration_intents', to='members.skill')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='member',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='members.profession'),
        ),
        migrations.AddField(
            model_name='member',
            name='registration_intent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member', to='members.registrationintent'),
        ),
        migrations.AddField(
            model_name='member',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='members', to='members.skill'),
        ),
        migrations.CreateModel(
            name='RenewalOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('consumed', models.BooleanField(default=False)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_otps', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['member', 'consumed', 'expires_at'], name='members_ren_member__e420a6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='registrationintent',
            index=models.Index(fields=['status', 'created_at'], name='members_reg_status_d55a58_idx'),
        ),
    ]
