# Generated by Django 4.2.30 on 2026-09-17 16:48

import apps.payments.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationNumberCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_number', models.CharField(blank=True, db_index=True, max_length=30, unique=True)),
                ('purpose', models.CharField(choices=[('REGISTRATION', 'New member registration'), ('RENEWAL', 'Membership renewal'), ('EVENT_TICKET', 'Event ticket')], max_length=20)),
                ('provider', models.CharField(choices=[('PAYHERO', 'PayHero (automatic — STK push)'), ('MANUAL', 'Manual M-Pesa (transaction code, admin-verified)'), ('DARAJA', 'Daraja (secondary, not yet audited)')], default='PAYHERO', max_length=20)),
                ('amount_kes', models.PositiveIntegerField()),
                ('phone_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PENDING_VERIFICATION', 'Pending manual verification'), ('PAID', 'Paid'), ('REJECTED', 'Rejected (manual review failed)'), ('SUSPICIOUS', 'Flagged as suspicious'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=20)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=100)),
                ('checkout_request_id', models.CharField(blank=True, max_length=100)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=50)),
                ('callback_token', models.CharField(default=uuid.uuid4, editable=False, max_length=64, unique=True)),
                ('access_token_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(blank=True, help_text='Set for renewals; null for a not-yet-settled registration.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='members.member')),
                ('registration_intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='members.registrationintent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payhero_api_username_enc', models.TextField(blank=True)),
                ('payhero_api_password_enc', models.TextField(blank=True)),
                ('payhero_channel_id_enc', models.TextField(blank=True)),
                ('payhero_callback_base_url', models.CharField(blank=True, max_length=300)),
                ('mpesa_consumer_key_enc', models.TextField(blank=True)),
                ('mpesa_consumer_secret_enc', models.TextField(blank=True)),
                ('mpesa_passkey_enc', models.TextField(blank=True)),
                ('mpesa_shortcode_enc', models.TextField(blank=True)),
                ('mpesa_environment', models.CharField(blank=True, default='sandbox', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('STK_PUSH', 'STK push initiated'), ('STATUS_CHECK', 'Status check'), ('CALLBACK', 'Callback received')], max_length=20)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('succeeded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='payments.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManualPaymentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_code', models.CharField(db_index=True, max_length=40, unique=True)),
                ('phone_number_used', models.CharField(max_length=20)),
                ('amount_submitted', models.PositiveIntegerField()),
                ('payment_date', models.DateField()),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to=apps.payments.models._manual_payment_screenshot_path)),
                ('confidence', models.CharField(choices=[('HIGH', 'High confidence — reference/amount/uniqueness all match'), ('MEDIUM', 'Medium confidence — needs a human look'), ('LOW', 'Low confidence — likely wrong or reused')], default='MEDIUM', max_length=10)),
                ('confidence_notes', models.CharField(blank=True, max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified — payment marked PAID'), ('REJECTED', 'Rejected'), ('SUSPICIOUS', 'Flagged as suspicious')], default='PENDING', max_length=12)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_submissions', to='payments.payment')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='payments_pa_status_343680_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(check=models.Q(('amount_kes__gt', 0)), name='payment_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='manualpaymentsubmission',
            index=models.Index(fields=['verification_status', 'submitted_at'], name='payments_ma_verific_ef68f9_idx'),
        ),
    ]
