# Generated by Django 4.2.30 on 2026-09-17 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('source', models.CharField(choices=[('REGISTRATION', 'Initial registration'), ('RENEWAL', 'Renewal'), ('ADMIN_GRANT', 'Manually granted by an admin')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_admin', models.ForeignKey(blank=True, help_text='Set only when source=ADMIN_GRANT.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='members.member')),
                ('payment', models.ForeignKey(blank=True, help_text='The settled payment that created this period. Null only for ADMIN_GRANT.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='payments.payment')),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['member', '-start_date'], name='memberships_member__876099_idx')],
            },
        ),
    ]
