# Generated by Django 4.2.30 on 2026-09-17 16:48

import apps.media_lib.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=apps.media_lib.models._safe_upload_path)),
                ('category', models.CharField(choices=[('GALLERY', 'Gallery'), ('HERO', 'Hero slide'), ('EVENT', 'Event image'), ('PAGE_BLOCK', 'Page block image'), ('OTHER', 'Other')], default='GALLERY', max_length=20)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
                'indexes': [models.Index(fields=['category', 'is_published'], name='media_lib_m_categor_6ea3ae_idx')],
            },
        ),
    ]
